#!/usr/bin/env python3
"""
Simple HTML creator for trading analysis results
"""

import os
from datetime import datetime

def create_simple_html():
    """Create a simple HTML version of trading analysis results"""
    
    content = ""
    if os.path.exists('trading_analysis_results.txt'):
        with open('trading_analysis_results.txt', 'r') as f:
            content = f.read()
    else:
        content = "No trading analysis results found. Please run the pipeline first."
    
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trading Signal Analysis Results</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 20px;
            background-color: #f5f5f5;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background-color: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #2c3e50;
            text-align: center;
            border-bottom: 2px solid #3498db;
            padding-bottom: 10px;
        }}
        .results {{
            background-color: #f8f9fa;
            border: 1px solid #dee2e6;
            border-radius: 5px;
            padding: 20px;
            margin: 20px 0;
            font-family: monospace;
            white-space: pre-wrap;
            overflow-x: auto;
        }}
        .emoji {{
            font-size: 1.1em;
        }}
        .summary {{
            background-color: #e8f4f8;
            border-left: 4px solid #3498db;
            padding: 15px;
            margin: 20px 0;
        }}
        .footer {{
            text-align: center;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #dee2e6;
            color: #6c757d;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🚀 COMPREHENSIVE TRADING SIGNAL ANALYSIS</h1>
        
        <div class="summary">
            <h3>📊 Analysis Overview</h3>
            <p><strong>Pipeline Status:</strong> Optimized Random Forest ML Pipeline with SHAP Explainability</p>
            <p><strong>Features:</strong> Stock Selection Expansion (3→10 stocks) + FRED Feature Name Simplification</p>
            <p><strong>Generated:</strong> {datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")}</p>
        </div>
        
        <div class="results">{content.replace('<', '&lt;').replace('>', '&gt;')}</div>
        
        <div class="summary">
            <h3>⚠️ Important Notes</h3>
            <ul>
                <li><strong>SHAP Emoji Indicators:</strong> 🟢 Positive impact, 🔴 Negative impact, ⚪ Neutral</li>
                <li><strong>FRED Features:</strong> Simplified names (e.g., "Unemployment" instead of "fred_UNEMPLOYMENT_m18_momentum")</li>
                <li><strong>Stock Coverage:</strong> Expanded analysis from 3 to 10 stocks</li>
                <li><strong>Confidence Levels:</strong> Based on model accuracy and feature importance</li>
            </ul>
        </div>
        
        <div class="footer">
            Generated by Optimized Random Forest ML Pipeline<br>
            Session: <a href="https://app.devin.ai/sessions/4fbfce1584a94376be1164d06cbf83c3">Devin AI Session</a><br>
            Requested by: @PremCouture
        </div>
    </div>
</body>
</html>"""
    
    html_filename = 'trading_analysis_results.html'
    with open(html_filename, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    print(f"✅ Created HTML results: {html_filename}")
    return html_filename

if __name__ == "__main__":
    create_simple_html()
